# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: fernflower
        path: build/libs/*
    - name: Create release
      id: create_release
      run: |
        set -xe
        shopt -s nullglob
        RELDATE="$(date +'%Y-%m-%d %H:%M')"
        NAME="fernflower build on $RELDATE"
        TAGNAME="autobuild-$(date +'%Y-%m-%d-%H-%M')"
        hub release create $(for a in artifacts/*.{jar}; do echo -a $a; done) -m "$NAME" -t "master" "$TAGNAME"
        echo "tag_name=${TAGNAME}" >> $GITHUB_OUTPUT
        echo "rel_date=${RELDATE}" >> $GITHUB_OUTPUT
      env:
          GITHUB_TOKEN: ${{ github.token }}
